apiVersion: v1
kind: Secret
metadata:
    name: ntfy-admin
    namespace: core
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:yrUM1MM0,iv:QP3sM371lkCryZukmNI+t7pSG7oUyiUZmD58R8JUJdg=,tag:wFxFIr7TO8BlUha/baR2vA==,type:str]
    password: ENC[AES256_GCM,data:D0ywFW6b6O0=,iv:ozNX9hJmESP/fdF2S7VsDSw9YI7X6POeftbnKpUqiN0=,tag:BcR3hDwNTqkXtsaQCb4LNg==,type:str]
    auth-users: ENC[AES256_GCM,data:RqXUC36jUnkC/CMZ9uBHcInTryenB2hfnM6d+yafPcPIOKAOsmcWuyUkyerFHDDf5A78bm242BIw2ooDPl9JuZFgCjnX9Efpcg==,iv:ZGLVmuZ2FzWzqsgFz+Hzg/vuqt/ybTZTYxqg9CFE0iI=,tag:kO25ZD999sRynH6S/+TiAg==,type:str]
sops:
    age:
        - recipient: age15enuwe3quuz6v7exl4wpkdlsyh9ucjsah90txzuvulzw42n2dazsqwgcce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUGpGMXY3US9VR290aFV0
            ZFlsaWRxd2FJeEduM09qU3BBb01WV0VIbkVJCkhVSXhKckdzUzB4QWNaVUZscmR6
            M3Vma1lWWVp3RENyTXF0bjFaL0FneDgKLS0tIDNUd1d1MXNSUk02TGgrbnBiSGhF
            SEtpUVRlT3c3QVVLR2dxSU9GWHgxL1UK+H2qhI4FpfCalM5PRg6Zb9mIwtt4FCXH
            ku1nA5geTISB19CmAGgU/AgFcwJB0r0XUgrbDcxqkId3HWfejgeq5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T21:50:45Z"
    mac: ENC[AES256_GCM,data:mhoOn9BBrJm4X2CBmEUkLfhNk9aWEOKZ3RvjPDcFoS2VkEQpQAuPE5E4BrIMlTVDiQcMmSEAsSrSLoVBryl6hG0a15Ixopk2wX6XoJk8L01IuVcA+jMCO7vxvgk/sV29+Po+ZO29DeTXA8jAxAR/+wE3EpBuMXYsy2WPg3fiCYI=,iv:8igpquOzmdXKlLO4I1nrohjK9CelSKhL78gbhn3pz+8=,tag:v5TcWCU5RLHGp7wHJa5IRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
