apiVersion: v1
kind: Secret
metadata:
    name: ntfy-admin
    namespace: core
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:yrUM1MM0,iv:QP3sM371lkCryZukmNI+t7pSG7oUyiUZmD58R8JUJdg=,tag:wFxFIr7TO8BlUha/baR2vA==,type:str]
    password: ENC[AES256_GCM,data:D0ywFW6b6O0=,iv:ozNX9hJmESP/fdF2S7VsDSw9YI7X6POeftbnKpUqiN0=,tag:BcR3hDwNTqkXtsaQCb4LNg==,type:str]
    auth-users: ENC[AES256_GCM,data:TbTIPxnQ54T55sG5huEXIFYVVgq9zTUd8sHxK6bSbDsaaxkwMPtqKan3gnaL22KClZTGWqYep0pQi9uTib4cvzQ1ihTM61GHquXbQP5hv3va4sSSS1NKsK7qC75PbB+ZyERhVghPSLKajC5ROlyWO/5IGmyAzo/p4Z6nDSPlZSAA+qpsiN97Wtz7+MY81XtAydvysNh8FLDV9EMGlw==,iv:B9xN2AZl0XgS4yPxus8g6UtUB13DBshHdrNFiWuvHAA=,tag:G4AjlMO7W86j5Jf4t1CSzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUGpGMXY3US9VR290aFV0
            ZFlsaWRxd2FJeEduM09qU3BBb01WV0VIbkVJCkhVSXhKckdzUzB4QWNaVUZscmR6
            M3Vma1lWWVp3RENyTXF0bjFaL0FneDgKLS0tIDNUd1d1MXNSUk02TGgrbnBiSGhF
            SEtpUVRlT3c3QVVLR2dxSU9GWHgxL1UK+H2qhI4FpfCalM5PRg6Zb9mIwtt4FCXH
            ku1nA5geTISB19CmAGgU/AgFcwJB0r0XUgrbDcxqkId3HWfejgeq5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15enuwe3quuz6v7exl4wpkdlsyh9ucjsah90txzuvulzw42n2dazsqwgcce
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T09:53:22Z"
    mac: ENC[AES256_GCM,data:AayZL8PHHlDpyYbuFEZxIlp5jlfUkG0R4o+xv+uciP8lRfaI9AWq+/xonWSZU8jh0a/r6DP8kaFCJdwEdB2DfjwC9IAM/LAr5axE7SfOa4q1ocYx+jzHMnSliuClcFZZmMXdDKKrAG6z1yjmwtLICTn+okNV+S/fAM4UTzM7Exg=,iv:Uy33SjEvafIY2GNHxB6TTo01WsIXFTNIdAgfNP1N+Z0=,tag:Cr9yzyqwFvNQdcLVyunIGQ==,type:str]
    version: 3.10.0
