apiVersion: v1
kind: Secret
metadata:
    name: ntfy-publisher
    namespace: core
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:LiWtjG0DKZJx9VP/FA6/RXM=,iv:3kDoRNhzOjtzDB7SHOyYfWNeeGH5CRRHG1LVSR+7/Nc=,tag:qAwxFBiXardVOtNjnChnRw==,type:str]
    password: ENC[AES256_GCM,data:5yjfFAKTGRa2c+QkOW0iy1U0atDhOc5oJ2Zun+nuG/AVMMLTZOAczUm8zcc=,iv:ErdfNCsNE9go4MZz/Dg87n2PsZ9YiFKyqvptAsatxnQ=,tag:rwT7z/Bnw+hCoWTonG5YCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNUNNeUNDRzNxc0VteWN2
            WVBIa0FWK3J1NkpSRXZZUmFESXAvZlM5bFJNClFadGxNNVIweGw3SVlOV05Gd243
            cVZ5bHh1VFlvdVFEcUFRK1hEbkR5bEEKLS0tIGdnNjN3TXMyOWxsNDdlWllQbFhn
            YjhDTTU3dWFKVno0TFhxU3cwdTVRT00KrMAAJSKoMuB+hNGi4p6ocrtD6dlUk1tg
            SjNDdQYyrakPBx10oseg7q1/BTZ3Dsaj0S049E/AfbJAKVNQfVuB5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15enuwe3quuz6v7exl4wpkdlsyh9ucjsah90txzuvulzw42n2dazsqwgcce
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T09:53:03Z"
    mac: ENC[AES256_GCM,data:f/Ub/akOBx/twTbmfpi54h3HoGyhsP0GjE2sJ0Vy1wgdEa6ya8umiq7ey81+JJ7L2UGtCIe1PdjfAqo1ztvseVGgb3sN6f2l57q1xhoOxAB1fnzzqO5avWiapQxlF57EG4/9Mw7pZFsW4PdrDapCrFGhCEYkBXL0qUN70SSLipA=,iv:LFLOkTpCv3w0gNTAZ5N2rzbx82Q+Qv7PA3qgr7UdhK4=,tag:J5qQXbkEKZGY82zqta3Aeg==,type:str]
    version: 3.13.2
