apiVersion: v1
kind: Secret
metadata:
    name: healthchecks-admin
    namespace: core
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8zeGm8Vf,iv:e1DZoW//qryhIlAWfIp3lNoowjlKk2DUciA/QB+4LNM=,tag:OdAjI0+FchtAQ5r+NPkisg==,type:str]
    email: ENC[AES256_GCM,data:YJdz2dU5oFejKcZj0XNWD+XCSRo=,iv:bC/9WX6oZkEAcNShElYykaxEunKbVq4JT1Or4Oq97KA=,tag:7gWh18OTPBrCkmW8pOaPHA==,type:str]
    password: ENC[AES256_GCM,data:zWk2A1iSu2g=,iv:augNMTnhWl+8fyUQFQ4JY7y9vmRalq1xZEfDp3ZdSGg=,tag:aIccd8/u2thDSSa0LD7rrQ==,type:str]
    secret-key: ENC[AES256_GCM,data:jMu4eN7QKhnbUq3EtNuIuyVRAqtoV0lLNTcdR7pMoAV7xA8oYjmTS8E1yFoVBBt7YcjVwIqi7p7FHdCL8KZeJw==,iv:fL74q+S+U1Peja3iY8vQYYGaOYQBUXiV1Kaors6cRU8=,tag:xLosUZRcM/Ewl2TCIsH/xQ==,type:str]
sops:
    age:
        - recipient: age15enuwe3quuz6v7exl4wpkdlsyh9ucjsah90txzuvulzw42n2dazsqwgcce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NlRTWE9CMXV0ZktabGFz
            SjYvdFVyWTRieVVURVB4ZE9OcmluZTFoV0JrCmtMZ29MWmtGeCtGWElvcjFQdyt2
            NGlNVXZabk9kekpwd1dXMkNIK3QweXcKLS0tIEd4Ym5zUWR0eXk0a2toaVdZUG5V
            bGRjcUFOZG42Mk42VUhzS3RoKzZremcK5r+05TrGXMNl1SX3QZckj4VuIZhNM6K1
            rCbKgJmXOchY+vtrFioPnsD/FMbnqiIxVEE6ztRZM8nbd2IpoWAvVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T21:50:45Z"
    mac: ENC[AES256_GCM,data:I2BSidrPbBGj71HdWZmnW1GMZpr/6DW+VRw3jPPR2UFxogrYFrCHbq7PrAHntFjhMbhVCGssDcvbNroXBPh2lAH/hP6PXcZjIuFo0+xBzXKn30AetZt5glZ/SAdj/or8hapDRIMMIiXHDIkT1zNFNngQvWPUUKwy/NM1BIlkLqs=,iv:NNflhZoRKK2PHnRlF7ajOBH6Dm13b3yQZZes4gbIGEI=,tag:GF6bsfJrFe17JEGLG0hqlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
