apiVersion: v1
kind: Service
metadata: {name: source-controller-metrics, namespace: flux-system}
spec:
  selector: {app: source-controller}
  ports: [{name: metrics, port: 8080, targetPort: http-prom}]
---
apiVersion: v1
kind: Service
metadata: {name: kustomize-controller-metrics, namespace: flux-system}
spec:
  selector: {app: kustomize-controller}
  ports: [{name: metrics, port: 8080, targetPort: http-prom}]
---
apiVersion: v1
kind: Service
metadata: {name: helm-controller-metrics, namespace: flux-system}
spec:
  selector: {app: helm-controller}
  ports: [{name: metrics, port: 8080, targetPort: http-prom}]
---
apiVersion: v1
kind: Service
metadata: {name: notification-controller-metrics, namespace: flux-system}
spec:
  selector: {app: notification-controller}
  ports: [{name: metrics, port: 8080, targetPort: http-prom}]
---
apiVersion: v1
kind: Service
metadata: {name: traefik-metrics, namespace: kube-system}
spec:
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  ports: [{name: metrics, port: 9100, targetPort: metrics}]
