apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-admin
    namespace: core
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:4qzAvqqU,iv:IvIaEV5RuqoApb3Mk4JNz2DFic5XBRcuAa0BviYwywk=,tag:+vVGs6dHYUrvh+vAKyeCgg==,type:str]
    password: ENC[AES256_GCM,data:TFRrVohwVR4=,iv:8a+7NjslHfAMwj5NVTylsDSRPXzexfrDIVk3D50Iplo=,tag:4K4Ko8hYaTP7T7Fms/mXkA==,type:str]
sops:
    age:
        - recipient: age15enuwe3quuz6v7exl4wpkdlsyh9ucjsah90txzuvulzw42n2dazsqwgcce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QzBBUFpKWUFidnE0WXQ5
            R1ZqMVI4c0RVdFFJRzl1bGdtcDZ4NFkwQWlRCm1LVDdzamJ5M2E0ZmJ0SE9IR2gx
            MlVIREQ0dG9qcXdMTWYvSFVnakllVEEKLS0tIHFVK0dQV3JiL2FLWDVETXFoWG01
            SXBQN2VTWGtGK3NMQ09RakU3dENFOTAKo1pQd88vfbfu5Lg6GsZBn8b6tEYJi3lh
            O4gW8OS0YxUrDO29nzfivsCwqrLEFZyknCE1NV6jkNdt4b1VwkdF+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T21:50:45Z"
    mac: ENC[AES256_GCM,data:TIPf/tPU89ssIMXYHgeZVXV0AGwL21zeBx41EqN7CdgFzUzut6NDMOWsRRYTxBejL32v1iOSlquo6YA7D1zsESsedCkmQGzn9iXomUZa6zMvRX76PJKnV15ouGqtNZkNOgj3TuIM4z7kAPOuICvuzcC1CDrRBYmO3uB+Q32Dvy8=,iv:o6Yu+5alyPp74gjZfsrj3amciDYuQoyEVaQh2A8KPyY=,tag:+uf9yDc3s+dUUecDJ+hbTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
