apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: core
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:5K7r42SH,iv:yjmPAPWt/yGruVsJJ/RSERUAVjJVfZhEhdiYw6MKOh0=,tag:H1qdoA4w/cOuots81KEvKw==,type:str]
    password: ENC[AES256_GCM,data:S+HDFMcSVhE=,iv:8KCph5TXvvc6KAL03Np4Qi1gdt7JQJVMAeLzmXXkUTg=,tag:ck0pLjcCVere9kMfz1X09g==,type:str]
sops:
    age:
        - recipient: age15enuwe3quuz6v7exl4wpkdlsyh9ucjsah90txzuvulzw42n2dazsqwgcce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT0lGeTRRbEtRaGxoeEFM
            a1pza1N2NnpESVlNNk1ISStuRXdtVkFENVJ3CjFDaE5GM1BaUStRcWFwTi9TakJN
            U0dCYmU1Q0pzVFJmZ3c3LzB6aGhZZkEKLS0tIEhtNTdwMmlYaUVIaHdLL3FUTkJH
            eDN4QU1aYnF3Y1BMWEFxS1VQbUR6NHMKAWJEF1MkdIOeBJqfiUUV0ydnA0U+BmIF
            vBuV9p4zK8ZpwAu07c3r8ELLEg9gs/EEAS+NtJLsc4QVXHjBUxUjMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T21:50:45Z"
    mac: ENC[AES256_GCM,data:hpaZEoQmD1mPDrVDsirSUi09pDus++5JcezBbywykVRVCTBpHJwuO9nj0hgaVaD2osLzTZB4deTYFfqXTp21wpr9L1wOWe30waj9KuxLlwa6VshmJLJHVLAzvALSWM+q3YdFNiDhDMQ+UW+uZ3fm0c4zhNePirmxi6j1Ej7bYNw=,iv:Le8rhtJ4pskan2nMLvm40FqRj2FFrNum7XQ64vH0yKY=,tag:+KD3GkWHDRPhqV4/awMvZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
