---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: cert-manager, namespace: flux-system}
spec:
  interval: 10m
  path: ./cluster/cert-manager
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: ingress, namespace: flux-system}
spec:
  dependsOn: [{name: cert-manager}]
  decryption: {provider: sops, secretRef: {name: sops-age}}
  interval: 10m
  path: ./cluster/ingress
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: platform-test, namespace: flux-system}
spec:
  dependsOn: [{name: ingress}]
  interval: 10m
  path: ./cluster/platform
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: uptime-kuma, namespace: flux-system}
spec:
  dependsOn: [{name: glance}, {name: ingress}]
  decryption: {provider: sops, secretRef: {name: sops-age}}
  interval: 10m
  path: ./cluster/apps/uptime-kuma
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: ntfy, namespace: flux-system}
spec:
  dependsOn: [{name: glance}, {name: ingress}]
  decryption: {provider: sops, secretRef: {name: sops-age}}
  interval: 10m
  path: ./cluster/apps/ntfy
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: healthchecks, namespace: flux-system}
spec:
  dependsOn: [{name: glance}, {name: ingress}, {name: ntfy}]
  decryption: {provider: sops, secretRef: {name: sops-age}}
  interval: 10m
  path: ./cluster/apps/healthchecks
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: prometheus, namespace: flux-system}
spec:
  dependsOn: [{name: ntfy}, {name: ingress}]
  decryption: {provider: sops, secretRef: {name: sops-age}}
  interval: 10m
  path: ./cluster/apps/prometheus
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: {name: grafana, namespace: flux-system}
spec:
  dependsOn: [{name: prometheus}]
  decryption: {provider: sops, secretRef: {name: sops-age}}
  interval: 10m
  path: ./cluster/apps/grafana
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  timeout: 5m
  wait: true
